name: CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Set up Spark
        run: |
          wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
          tar -xvzf spark-3.1.2-bin-hadoop3.2.tgz
          sudo mv spark-3.1.2-bin-hadoop3.2 /opt/spark
          echo "SPARK_HOME=/opt/spark" >> $GITHUB_ENV
          echo "PATH=$SPARK_HOME/bin:$PATH" >> $GITHUB_ENV
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: generate_and_push
        run: make generate_and_push
      - name: deploy
        run: make deploy
