name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install OpenJDK 11
      - name: Install OpenJDK 11
        run: sudo apt-get install openjdk-11-jdk -y

      # Set JAVA_HOME and SPARK_LOCAL_IP environment variables
      - name: Set JAVA_HOME and SPARK_LOCAL_IP
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
          echo "SPARK_LOCAL_IP=127.0.0.1" >> $GITHUB_ENV

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: install packages
        run: make install

      # Run lint
      - name: lint
        run: make lint

      # Run tests
      - name: test
        run: make test

      # Run code formatting
      - name: format
        run: make format

      # Generate and push changes
      - name: generate_and_push
        run: make generate_and_push

      # Deploy step (customize this as per your needs)
      - name: deploy
        run: make deploy
